[platformio]
default_envs = pico

# ============================================================================
# Build Environments for Different Hardware Configurations
# ============================================================================

# Single Endless Motor (Current Hardware - Trim-like)
[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
board_build.core = earlephilhower
framework = arduino
lib_archive = no


[env:pico_tinyUSB]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
board_build.core = earlephilhower
framework = arduino
lib_archive = no
build_flags =
    -DUSE_TINYUSB
    -DCFG_TUSB_CONFIG_FILE=\"my_tusb_config.h\"
    -Iinclude/

